tokuhirom/Minilla

- README.md
- lib/Minilla.pm
> not bin/ but script/ when ModuleBuildTiny

- lib/Minilla/Project.pm
- t/project/badge.t
Travis's badge is flat style however coveralls one is not.
It's a bit ugly, so change to be uniform.
Before
After
> Use flat-style badge of coveralls

- lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm
* Slighly tweaked the way falling back _REQUIRES to PREREQ_PM (code copied from Dist::Zilla)
* Do not request higher MakeMaker in configure_requires
* Do not set NO_MYMETA since MakeMaker (CPAN::Meta) creating MYMETA is just fine
* Only requires what's in 'requires' type, since the default includes 'recommends'
(No extensive tests have been done on my end)
> MakeMaker improvements

- lib/Minilla/Project.pm
- t/project/badge.t
Codecov is something like Coveralls.
> Support to generate codecov's badge.

- lib/Minilla/Release/CheckChanges.pm
Otherwise it looks like the author needs to add the actual next version and that doesn't work.
> Clarify CheckChanges message

- lib/Minilla/Project.pm
> Use LANG=C to get the repository URL git

- README.md
- lib/Minilla.pm
> Use https scheme for avoiding Bot PR

- lib/Minilla.pm
- lib/Minilla/Project.pm
- t/project/badge.t
AppVeyor can test on Microsoft Windows. I often test my Perl library in AppVeyor.
> Support to generate appveyor's badge.

- lib/Minilla/Metadata.pm
- t/05_metadata.t
This is related to #184.
@assistcontrol Could you check this change ?
> License case issue

- lib/Minilla/ModuleMaker/ModuleBuild.pm
This is squashed commits #191.
> Squashed #191 commits

- t/project/contributors.t
- t/work_dir/release_test.t
> Fix removing environment variables issue

- README.md
- lib/Minilla.pm
> Add shell completion file documentation

- README.md
- lib/Minilla.pm
- lib/Minilla/Project.pm
- t/project/badge.t
And refactoring badge conditions
> Support CircleCI badge

- lib/Minilla.pm
- lib/Minilla/Project.pm
- t/project/badge.t
- cherry-picked #202 commits
- Update it for latest badge implementation
> Update PR 202

- .travis.yml
- lib/Minilla/Profile/Base.pm
Now travisci has perl 5.26! https://github.com/travis-ci/travis-ci/issues/7825
> add perl 5.24, 5.26 to travis.yml

- lib/Minilla/Project.pm
- t/project/badge.t
Just a small cosmetic change, but helps to show what the badge is for.
> :lipstick: add logo to AppVeyor badge

- lib/Minilla/ModuleMaker/ModuleBuild.pm
- t/module_maker/c_source.t
> set c_source only if it is defined

- lib/Minilla/Project.pm
- t/project/meta.t
> Pass features from cpanfile to optional_features in META.json

- t/project/static_install.t
https://github.com/tokuhirom/Minilla/pull/245 again.
I forgot to add CLEANUP => 1 in t/project/static_install.t.
> remove temp directories in test

- lib/Minilla.pm
- lib/Minilla/Project.pm
Add kritika badges with different types support.
> Add kritika badge

- lib/Minilla/Release/BumpVersion.pm
- t/cli/release_no_bump_versions.t
>  do not bump versions of files which are listed as no_index

- lib/Minilla/ReleaseTest.pm
> Older Test::Pause::Permissions may have bugs. we need to depend on the

- README.md
- lib/Minilla.pm
- lib/Minilla/Project.pm
- t/project/badge.t
Add new badge support for GitHub Actions.
https://help.github.com/en/articles/about-github-actions
> add badge for github actions

- lib/Minilla/Profile/Base.pm
* remove `sudo: false`
* set `dist: trusty` for perl <= 5.20
> update .travis.yml template

- .travis.yml
- lib/Minilla/Profile/Base.pm
See also https://github.com/libwww-perl/WWW-Mechanize/pull/279#issuecomment-604768734
> now travis xenial environment supports perl 5.14+

- README.md
- lib/Minilla.pm
> Fix cpan-upload link

- lib/Minilla/Tutorial.pod
Make 'minil release' work again.
> makes 'minil release' work again

- lib/Minilla.pm
Added '--with-recommends' at a second point in the documentation.
> updated documentation to make 'minil release' work

- t/module_maker/eumm.t
- t/module_maker/tiny.t
This suppresses github action warnings
> Don't run tree command if it is not installed

- README.md
- lib/Minilla.pm
- lib/Minilla/CLI/Release.pm
- lib/Minilla/Release/CheckReleaseBranch.pm
- t/cli/release_check_branch.t
If `release.branch` is set, check if the current branch matches that release branch.
We can use `release.hooks` to check if the release branch is correct, but it's better to notice mistakes before editing Changes.
> Check release branch

- lib/Module/BumpVersion.pm
- t/bumpversion.t
> Support package version syntax

- lib/Minilla.pm
I recently tried Minilla and it fits my needs almost perfectly. Great work.
> documentation for for module_maker option in configuration section
