lib/Minilla/Git.pm
t/filegatherer.t
t/filegatherer/submodules-recursive.t

Isses:
* Could not solve the recursive submodule.
* Outputting the incorrect results when multiple submodules contains.
Solutions:
* Gathers files on submodule recursive.
* Fix to required format when multiple submodules contains.
`git ls-files -z` does *NOT* print new line in last.
So it breaks format when multiple submodules contains and combined with `git submodule foreach`. (and failed to parse.)

Gathers files on submodule recursive. And fixed the issue that occurs when multiple submodules contains.

---

lib/Minilla/CLI/Clean.pm
lib/Minilla/Profile/Base.pm

* ExtUtils::MakeMaker creates `pm_to_blib` file, so ignore it.
* `minil clean` cleans `Makefile` and `pm_to_blib` too.

tiny fixes for ExtUtils::MakeMaker

---

lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm

Executable files would not be installed unless we specify them in EXE_FILES attribute.

add missing EXE_FILES attribute for EU::MM

---

cpanfile
lib/Minilla.pm
lib/Minilla/Project.pm

* README.md is generated from your pod by Pod::Markdown.  You can
use a different module, such as Pod::Markdown::Github, by setting the
markdown_maker in your minil.toml.  The module must be a subclass of Pod::Markdown.

add markdown_maker config key

---

lib/Minilla/Project.pm

* The contributors list is generated by parsing the output of `git
log`. Calling `git log` on a repository with no commits produces the
message "fatal: bad default revision 'HEAD'".  Check to see if HEAD
exists before trying to generate the contributors.  If no HEAD,
return an empty array.

silence test warnings relating to git log

---

.travis.yml
Build.PL
META.json
README.md
cpanfile
lib/Minilla.pm
lib/Minilla/Migrate.pm
lib/Minilla/Project.pm
minil.toml
t/cli/regenerate_BuildPL.t
t/dist/Acme-FooXS.dat
t/module_maker/PL_files.t
t/module_maker/allow_pureperl.t
t/module_maker/c_source.t
t/module_maker/tap_harness_args.t
t/module_maker/xsutil.t
t/project/xsutil.t

Even when minil.toml does not exist or module_maker is not set, make sure to use MBT by default.
There's a backward compat detector so that if custom builder or XSUtil options are set in minil.toml, it falls back to ModuleBuild with a big warning suggesting to set `module_maker` in the config file.
It also makes sure `minil.toml` is created in `minil migrate`, unlike only when there's a dist.ini file.
This switches Minilla itself to use MBT as well.
Fixes #164

Use Module::Build::Tiny as a default module maker

---

lib/Minilla.pm

This makes Minilla more opinionated, and it is better to state so, rather than implicitly requiring 5.8.1 due to the build tool requirement (i.e. CPAN::Meta)
Fixes #167

Doc: Add perl 5.8.1 requirement in the assumption

---

lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm
lib/Minilla/ModuleMaker/ModuleBuild.pm
lib/Minilla/Project.pm
t/module_maker/allow_pureperl.t

This bumps up the configure requirement for Module::Build and MakeMaker that supports test requires and MYMETA generation and merge, so that all the hacks inside Build.PL/Makefile.PL runtime can be eliminated. 
Fixes #168

Require newer MB/MM and remove the hack in build script

---

lib/Minilla/CLI/New.pm

Module::Build is no longer the default builder.

Update default builder

---

lib/Minilla/ModuleMaker/ModuleBuild.pm

Otherwise it is always 'perl' while META.json
contains correct value. This may be confusing.

Generate proper license in Build.PL

---

lib/Minilla/Profile/Base.pm

Travis CI has already supported Perl 5.22 :+1:

Add Perl 5.22

---

t/project/contributors.t
t/work_dir/release_test.t

Both 'git.config' and environment variables are set, then
environment variables are used, this causes test failure.
This is related to #187.

Always use 'git.config'

---

t/dist.t

Delete system() function call.
Some operating system don't have 'cat' cmd.
Only fix warning.
Before. (`windows 10` and `strawberry perl 5.22.1.3 / 64bit`)
```
$ prove -lc t\dist.t
t\dist.t .. 'cat' is not recognized as an internal or external command,
operable program or batch file.
t\dist.t .. ok
All tests successful.
Files=1, Tests=1,  4 wallclock secs ( 0.03 usr +  0.00 sys =  0.03 CPU)
Result: PASS
```
After.
```
$ prove -lc t\dist.t
t\dist.t .. ok
All tests successful.
Files=1, Tests=1,  5 wallclock secs ( 0.03 usr +  0.02 sys =  0.05 CPU)
Result: PASS
```

Delete system() function call

---

lib/Minilla/ModuleMaker/ModuleBuild.pm

As is well-known, keys() function of Perl 5.18+ returns keys randomly.
So `minil build` may generate different Build.PL each time. 
This PR suppresses this by sorting keys.
I found this while building https://github.com/gfx/Perl-Data-Util.

To suppress useless git diff, sort keys in Build.PL

---

cpanfile
lib/Minilla.pm
lib/Minilla/Project.pm
t/project/badge.t

To enable this feature, while specifying a CI provider in `badges`, the user can include additional parameters as a query string:
```
badges: [ "travis?token=xxxxyyyyzzzz&branch=dev" ]
```
We can add this support for other CI providers supported by Minilla as well.

Additional badges parameters for Travis CI

---

lib/Minilla/Project.pm
t/project/badge.t

Some perl repositories are named like p5-Foo-Bar, but its module
name is Foo::Bar(Foo-Bar). Badge URL of such modules are invalid.
CC: @zakame

Use module name instead of repository name for metacpan badge

---

lib/Minilla/Util.pm

`cmd_perl` passes library paths from @INC excludes it listed in sitelibexp, sitearchexp, privlibexp  and archlibexp. But it causes an issue on ubuntu. It shares library directories with some Perl versions.
gfx, the original implementor of `cmd_perl`, says there's no reason to filter sitelibexp, sitearchexp, privlibexp  and archlibexp. As a result, we should remove this filter.
Here's a chat log(You can read following logs with Google Translator)
gfx @tokuhirom そのロジック、どこかから拝借してきた気がするんだよね…。
[9:15 AM]
tokuhirom そんな感じのコードではあるが、出所不明すぎるw
[9:16 AM]
gfx うーむ。全然覚えてない。
[9:20 AM]
charsbar https://metacpan.org/source/GFUJI/lib-xi-1.03/lib/lib/xi.pm#L25-38
[9:20 AM]
これがさらにどこから来たのかはわからんけど。
[9:22 AM]
tokuhirom やる意味はないと思うんだよね
[9:22 AM]
なんか謎のこだわりっぽさある
[9:23 AM]
gfx おー
[9:23 AM]
いや、それ見たら思い出した！やっぱり、単にもともと …

Remove @INC optimization. It doesn't work on ubuntu( #205 ).

---

script/minil

If we use `#!perl`, then toolchains will rewrite it in installation time.
If you intentionally use the env shenbang, please ignore this PR. Thanks.

fix shebang so that toolchains rewrite it

---

lib/Minilla.pm
lib/Minilla/Project.pm
t/project/meta.t

This PR allows 'Metadata' section in minil.toml, so that we can adds keys to META.json/META.yml.
Especially, I want to set x_static_install true in minillalized distribution.

allow 'Metadata' section in minil.toml

---

lib/Minilla/Metadata.pm
t/project/meta.t

fix #198 
As in #198, if a pm file contains `use v5.20;`, then minilla produces META.json containing
```
"prereqs" : {
...
"runtime" : {
"requires" : {
"perl" : "5.20"
}
},
```
which means this distribution requires perl 5.200_000.
This PR fixes this issue by extracting perl version together with leading "v".

fix how to extract perl version from v-string

---

t/Util.pm

Because if GIT_CONFIG is set, 'git config' command uses its file instead
of .git/config. So some tests which check .git/config content are failed
in such case.
This fixes #211

Unset GIT_CONFIG environment variable

---

lib/Minilla/ModuleMaker/ModuleBuild.pm

`@INC` does not contain current directory from Perl 5.25.9.
This is related to #215.

Push '.' to @INC when custom builder is used

---

lib/Minilla/Project.pm
t/project/contributors.t

Currently the order of x_contributors is the same as `git log --format="%aN"`.
Then it happens that `minil build` emits a different META.json even though the contributors are same.
This PR prevents this by sorting x_contributors section.

sort x_contributors section to avoid unnecessary diff

---

lib/Minilla/Project.pm
t/project/badge.t

I just found out that AppVeyor does a `$repository_name ~= s/\./-/g` so
take account for that when regenerating the badge.

Handle AppVeyor renaming repository

---

lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm
lib/Minilla/ModuleMaker/ModuleBuildTiny.pm

This PR fixes the following tests in Windows.
* t\module_maker\eumm\run_tests.t
* t\module_maker\eumm\run_tests.t
This failure is reported below.
It probably occurs only on Windows.
* perl 5.20.1
* http://www.cpantesters.org/cpan/report/a30c8c13-6c02-1014-a592-7e642c68c8d8
* perl 5.24.0
* http://www.cpantesters.org/cpan/report/f20e8bf2-6bf3-1014-b125-bc6d1e4a1ad6
https://ci.appveyor.com/project/sago35/minilla/build/1.0.18
```
```
https://ci.appveyor.com/project/sago35/minilla/build/1.0.21
----
File::Spec's pod says `If $base is not present or '', then Cwd::cwd() is used.`,
but there is a difference in strawberry perl (windows).
I don't know why.
* File::Spec rel2abs()
* https://metacpan.org/pod/File::Spec#rel2abs()
* test code
* https://github.com/sago35/Minilla/commit/401e2a9ba00d61a28b18 …

Fix an issue where run_tests.t fails on Windows

---

README.md
cpanfile
lib/Minilla.pm
t/dist.t

- Drop Test::MinimumVersion
- Add Test::MinimumVersion::Fast
Test::MinimumVersion is no longer used and Test::MinimumVersion::Fast is used
on release testing.

Adjust dependency around release testing

---

lib/Minilla/Project.pm

The `Pod::Markdown->parse->as_markdown` returns Perl string, so
use the spew_utf8 function to avoid `Wide character in print`
warnings when multibyte is described in `pod`.

suppress `Wide character` warnings while regenerating README.md

---

lib/Minilla.pm
lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm
lib/Minilla/ModuleMaker/ModuleBuild.pm
lib/Minilla/ModuleMaker/ModuleBuildTiny.pm
lib/Minilla/Project.pm
lib/Minilla/Unsupported.pm
t/module_maker/eumm/unsupported.t
t/module_maker/tiny/unsupported.t
t/module_maker/unsupported.t
t/project/unsupported.t

`os_unsupported` API is added on EUMM 7.26.
By setting `unsupported.os` value to add unsupported OS checks for (Build.PL|Makefile.PL).

add os_unsupported support

---

lib/Minilla/ReleaseTest.pm

`minil release` failed author tests at dev version release (e.g. `0.02_01`) as below:
```
t/00_compile.t ................ ok
xt/minilla/cpan_meta.t ........ ok
xt/minilla/minimum_version.t .. ok
xt/minilla/permissions.t ...... skipped: (no reason given)
xt/minilla/pod.t .............. ok
xt/minilla/spelling.t ......... skipped: no ~/.spellunker.en
Test Summary Report
-------------------
xt/minilla/permissions.t    (Wstat: 65280 Tests: 0 Failed: 0)
Non-zero exit status: 255
Files=6, Tests=7, 160 wallclock secs ( 0.03 usr  0.02 sys +  2.92 cusr  0.75 csys =  3.72 CPU)
Result: FAIL
```
`Test::PAUSE::Permissions` provides an option for dev version release and I fixed to set dev mode in `xt/minilla/permissions.t`.

fix permissions test at dev version release

---

lib/Minilla/Metadata.pm

This fixes the case where "authors" might accidentally get extracted from the description for a function named 'author'.
Ref #240

Only extract authors from =head1

---

lib/Minilla/Project.pm

I develop Minilla in `~/src/github.com/tokuhirom/Minilla` directory.
Then running test emits a lot of warnings:
```
❯ prove -l t/cli/regenerate_BuildPL.t
t/cli/regenerate_BuildPL.t .. Use of uninitialized value $user in concatenation (.) or string at /home/skaji/src/github.com/tokuhirom/Minilla/lib/Minilla/Project.pm line 510.
Use of uninitialized value $repo in concatenation (.) or string at /home/skaji/src/github.com/tokuhirom/Minilla/lib/Minilla/Project.pm line 510.
Use of uninitialized value $user in concatenation (.) or string at /home/skaji/src/github.com/tokuhirom/Minilla/lib/Minilla/Project.pm line 511.
Use of uninitialized value $repo in concatenation (.) or string at /home/skaji/src/github.com/tokuhirom/Minilla/lib/Minilla/Project.pm line 511.
Template error: Use of …
```

minor fix:  do not count file:// repository as github

---

lib/Minilla.pm
lib/Minilla/CLI/New.pm
lib/Minilla/Project.pm
t/project/static_install.t

Now milla sets x_static_install 1 if it is appropriate.
https://metacpan.org/release/MIYAGAWA/Dist-Milla-v1.0.19
I am happy if Minilla follows that.
In this PR:
If `static_install = "auto"` is specified in minil.toml (or nothing is specified), then minil tries to detect whether distributions are ready for static install or not, and set `x_static_install` accordingly.
If users specify `static_install = 0/1` explicitly, then minil will respect it.
@tokuhirom Feel free to reject this PR.
See also
* The spec of static install: https://github.com/Perl-Toolchain-Gang/cpan-static
* A Dist::Zilla plugin for static install: https://metacpan.org/pod/Dist::Zilla::Plugin::StaticInstall

Set x_static_install 1 if it is appropriate

---

lib/Minilla/Git.pm
lib/Minilla/Project.pm
t/project/in_submodule.t

This fixes an issue where `minil` would try to act on the parent module rather than the submodule when in the submodule’s directory.
When inside a Git submodule, `.git` is a file, not a directory.  By asking Git itself for the top level, we don’t have to worry about such complications.

Ask Git for the top level, rather than inferring from .git/

---

lib/Minilla.pm
lib/Minilla/Project.pm
minil.toml
t/project/badge.t

Now travis-ci.com supports the GitHub Checks API, which is available to open source projects.
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com
This PR adds support for travis-ci.com badge to Minilla;
it introduces explicit keywords `travis-ci.com` and `travis-ci.org` for `badges` in minil.toml.
That is,
* `badges = ['travis-ci.com']` generates travis-ci.com badge
* `badges = ['travis-ci.org']` generates travis-ci.org badge
Note that for backward compatibility, `travis` keyword still means travis-ci.org.

support travis-ci.com badge

---

lib/Minilla/Release/Commit.pm

When "Changes" file diff happens to end with empty lines, they are removed by commit command and consequently produce technically inaccurate data.  It also removes trailing spaces at the end of line.
This fix should work fine but "git show/log" command still removes whitespaces before producing output.  It has to be addressed someway but now I can only think of using "git cat-file" to check.

Use '--cleanup=verbatim' option with commit not to erase empty line in diff output.

---

README.md
lib/Minilla.pm

Hello,
First thank you a lot for this great tool !!! :heart: 
Some features won't work if your remote is not named origin. 
If you have only one remote but it is named "central", `minil test` won't be able to generate badges for instance.
This pull request is the very minimum (document the convention).
I tried to do more than that (adding a check) but it's not clear what would be the best approach :
- If I add a check in sub **CheckOrigin** (currently only check that a remote is set, not the name of it), it seems it will be only be executed during Release action.
- If I add a check in **check_git** it will be executed for every actions even if some of them do not require to access the remote url.
- We can add another sub **check_git_origin** and add it as a step of some actions (which …

It is a conventaion that the remote should be named origin

---

README.md
lib/Minilla.pm
lib/Minilla/Project.pm

Hello,
This pull request adds support for gitlab badges (pipeline and coverage). 
Somebody opened an issue about it : #285  
Currently the link is https://gitlab.com/$user_name/$repository_name/-/commits/master as documented in gitlab settings but we could imagine using also https://gitlab.com/$user_name/$repository_name/pipelines 
Best regards.
Thibault

Add gitlab badges

---

lib/Minilla/Release/CheckChanges.pm

When running `minil release`, the `{{$NEXT}}` line in a Changes file must meet all the criteria.  This commit adds code to tell the user what the specific problem is if the `{{$NEXT}}` line does not meet all the criteria.
For example, 
{{$NEXT}}
1.01 2001-02-03
Some change
is invalid, because there are no changelog entries under `{{$NEXT}}`.  However, the current code says `No mention of {{$NEXT}}`, even though `{{$NEXT}}` is in the file.  I believe this change will reduce user confusion.
This PR also includes the fix in #260, so that it can be applied cleanly after #260.

{{$NEXT}}: describe detailed error

---

lib/Minilla/Metadata.pm
t/project/in_submodule.t

Currently, the author's name is taken from the LICENSE section if it appears earlier than the AUTHOR section.
I believe it is not intentional behavior.
This code makes it always look at the AUTHOR section if it exists.
I added minimal updates in other regex parts.

Take author name from AUTHOR section even if it appears later.

---

lib/Minilla/Project.pm
t/project/badge.t

If `release.branch` is set, it would be more natural to refer to that as the URL for the badge as well. Recently, more and more repositories are not using master.
(We should also think about the appropriate default branch and how to detect them, but we won't cover that here.)

the badge URLs refers to the release.branch setting

---

lib/Minilla/Release/CheckOrigin.pm

I add a strict check for the remote name in CheckOrigin because, by convention, Minilla requires that the remote name is "origin".

In CheckOrigin.pm, make sure that there is a remote named 'origin'.

---

lib/Minilla/Release/BumpVersion.pm
t/release/bump_version.t

When we type in a new version into a console, the release will proceed even if its format is incorrect.
Recently I tried to release "v1.0.0" in my module but accidentally released "1.0.0".
To prevent this kind of happening, I suggest doing a compatibility check before bumping.
Since the user sometimes wants to change the version format, we will only prompt them and they can ignore it.

Just before bumping the version, check the format compatibility of the versions

---

lib/Minilla/Release/BumpVersion.pm

Sorry. I didn't check it enough and there was a little warning, so I'll fix it. This is the last in my series of fixes. Thank you for all your help.

surppress warnings of Redundant argument in sprintf

---

README.md
lib/Minilla.pm
lib/Minilla/Project.pm
lib/Minilla/Release/CheckReleaseBranch.pm
t/project/badge.t

Minilla initially has a convention that the master branch is the release branch, but that is no longer used except for badge URL generation. Also, the practice of using master as the default branch has depreciated in general.
Therefore, I propose to abolish this convention.
It is enough for the badge URL generation to use the "config.release.branch" or extract the default branch from the output of  `git remote show origin`. I've made those changes.
An unintended side effect of this change is that the generated badge URLs may change, but it is not a critical issue and is acceptable.

Detect default branch from "origin" and remove the convention of release branch as "master"

---

lib/Minilla/Project.pm
t/project/meta.t

https://github.blog/2021-09-01-improving-git-protocol-security-github/
It seems that GitHub will disable `git://` at March 15, 2022.
So let's use `https://` instead.

use https for github/gitlab urls

---

lib/Minilla/Project.pm
t/project/meta.t

In #315, I changed the git url protocol from `git://` to `https://`.
OTOH, CPAN::Meta fills in the repository type `git` only if the url starts with `git://`.
https://github.com/Perl-Toolchain-Gang/CPAN-Meta/blob/67802250f9d6556b5b219684e9bc8f68588459ce/lib/CPAN/Meta/Converter.pm#L672
So I should have specify repository type `git`.

specify repository type

---

lib/Minilla.pm
lib/Minilla/Project.pm
minil.toml
t/project/badge.t

At some point, it seems that github changes the badge url of github actions.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
before: https://github.com/tokuhirom/Minilla/workflows/test/badge.svg
after: https://github.com/tokuhirom/Minilla/actions/workflows/test.yml/badge.svg
This PR follows it.

update github actions badge url

---

lib/Minilla/Profile/Base.pm
lib/Minilla/Profile/ExtUtilsMakeMaker.pm
lib/Minilla/Profile/ModuleBuild.pm
lib/Minilla/Profile/ModuleBuildTiny.pm
lib/Minilla/Profile/XS.pm
lib/Minilla/Project.pm
t/03_step.t
t/profile-xs.t

This pull request changes CI from Travis to GitHub Actions.
Note:
I considered making both Travis and GitHub Actions available for compability. However, I thought it would be better to keep Minilla simple, so used only GitHub Actions.

Change from Travis to GitHub Actions

---

lib/Minilla/Profile/Base.pm

Minilla defaults to create distributions with Module::Build::Tiny's Build.PL.
While Minilla correctly adds Module::Build::Tiny as a configure dependency to META.json,
if we manually execute Build.PL, we need to install Module::Build::Tiny first.
Let's simply use `prove` in github actions template.

use just "prove" in github actions template

---

lib/Minilla/Git.pm
t/filegatherer/submodules-recursive.t
t/lib/Util.pm

Since git 2.38.1, cloning from local file is disabled by default for security issue. This makes tests fail. So set 'protocol.file.allow=always' for avoiding this issue.
And move 'git_submodule_add' utility function to 't/Util.t' because it is used only from test code.
Reference
- https://github.com/tokuhirom/Minilla/issues/322#issuecomment-1311702767
- https://github.com/tokuhirom/Minilla/issues/322#issuecomment-1311772119

Fix for git 2.38.1 or higher versions

---

lib/Minilla/Release/Commit.pm

Current code gets branch name by parsing HEAD file for older git. However developers no longer use such old git. 1.17.0 was released 10 years ago(2012/APR/7).
Close #322 
Reference
- https://github.com/tokuhirom/Minilla/issues/322#issue-1390173116

Use git command to get branch name instead of parsing HEAD file

---

.github/workflows/test.yml
lib/Minilla/Profile/Base.pm

actions/checkout@v2 uses Node.js 12, which is deprecated.
So let's use actions/checkout@v3.

use actions/checkout@v3

---

cpanfile
lib/Minilla.pm
lib/Minilla/Project.pm
minil.toml

Now PAUSE itself copies the permissions from the "main module"
to any new modules entering the index for the first time,
so we don't need to set x_authority anymore.
See
https://github.com/andk/pause/pull/222
https://github.com/karenetheridge/Dist-Zilla-Plugin-AuthorityFromModule/commit/dad604f7cf0fa502a4553bcdcada01193c4f626f

do not set x_authority by default

---

lib/Minilla.pm
lib/Minilla/Project.pm

Specify arguments to pass to `markdown_maker`'s **`new()`** constructor
Example:
```
[markdown_maker_opts]
local_module_re = "^MyApp::"
local_module_url_prefix = "https://example.org/perl/pod/"
```

Add `markdown_maker_opts` Config Hash

---

LICENSE
lib/Minilla/License/Perl_5.pm

This PR updates the Perl_5 license text by:
```
❯ perl -MSoftware::License::Perl_5 -e 'print Software::License::Perl_5->new({holder => q[$holder], year => q[$year]})->fulltext'
```

update Perl_5 license text

---

Changes
lib/Minilla/Project.pm
t/project/badge.t

The URLs associated with workflow names have been deprecated and now return a 404 error. So, I have changed the URLs to be derived from the workflow file names. This URL format is documented and stable.
Ref. https://docs.github.com/en/actions/how-tos/monitor-workflows/add-a-status-badge

Update GitHub Actions status badge URLs to match the latest documentation
